### ISSUE TITLE
flesh out README.md

### ISSUE THREAD

**Issue by brooksandrew** [dkkiva/models#1]
Add introduction to project, so that new volunteers can quickly onboard and get up to speed.

just some ideas of things to add:
* how to access data
* descriptions of data 
* add links to docs in Google Drive
* add a how to contribute sections...(one approach could be to have volunteers check open issues and assign themselves to one.  if there's no open issues of interest, invite them to open one themselves and start working on it, contribute code to repo)

**Comment by kgilvi3** [comment]
@Jonathan-Joa saw you working on a Readme in GoogleDrive -- I'll drop some stuff in there instead of having competing branches

**Comment by kgilvi3** [comment]
Added a few more deets to the README doc and put some of the purpose statements in. Did not go more deeply into the individual models (makes more sense to do that as we make 'em)
